import React from 'react';
import cn from 'classnames';
import '@fontsource/inter';
import font from '../styles/fonts.module.css';
import { HeaderBar } from '@/components/HeaderBar';
import { FooterBar } from '@/components/FooterBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <HeaderBar />

      {children}

      <FooterBar />
    </div>
  );
}
